title: Robotics for everyone!
author: Ashi Tharuka
email: your-email@domain.com
description: > #Robotics for kids allows children to learn STEM concepts in a hands-on environment. 
They learn how to program, design, and make their own robots. 
Robotics offers an educational tool for kids to think out of the box. 
Many times kids have ideas of what they dream to create. (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
